// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rywfrcbfzhodlcckqziw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5d2ZyY2JmemhvZGxjY2txeml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzcyNjEsImV4cCI6MjA2NDI1MzI2MX0.0X7BtyC9B43WPeR9Q_4epnxuwwWdGJIc3CeQIjEUldI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);